# Generated by Django 5.1.1 on 2024-10-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_product_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('emprendedor', 'Emprendedor'), ('pyme', 'Pyme'), ('admin', 'Administrador')], default='emprendedor', max_length=20),
        ),
    ]
