# Generated by Django 5.1.1 on 2024-10-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_product_user_service_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='business_type',
            field=models.CharField(choices=[('products', 'Productos'), ('services', 'Servicios'), ('both', 'Ambos')], default='both', max_length=10),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
