import spacy
from spacy.training.example import Example
import random
import os

# Cargar el modelo base de español de spaCy
nlp = spacy.blank('es')

# Agregar el componente de clasificación de texto
if "textcat" not in nlp.pipe_names:
    textcat = nlp.add_pipe("textcat_multilabel", last=True)
else:
    textcat = nlp.get_pipe("textcat")

# Agregar las etiquetas para las categorías de intención
textcat.add_label("product_query")
textcat.add_label("service_query")
textcat.add_label("price_query")

# Conjunto de datos de entrenamiento: 10 ejemplos por categoría
train_data = [
    ("Me interesa saber más sobre sus productos", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Qué productos tienes a la venta?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Muéstrame los productos disponibles", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Quiero un listado de productos", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Cuáles son los mejores productos?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Estoy buscando productos nuevos", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Enséñame algunos productos", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Tienen productos disponibles ahora?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Quiero comprar un producto", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Qué productos puedes ofrecerme?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Estoy interesado en sus productos", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Qué productos ofrecen?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Quiero saber más sobre su catálogo de productos", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Tienen productos para empresas como la mía?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Busco un producto específico, ¿pueden ayudarme?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Me pueden mostrar sus productos más vendidos?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Necesito información sobre sus nuevos productos", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Qué productos recomiendan para mi negocio?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Estoy buscando productos ecológicos", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Quisiera ver su lista de productos", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Ofrecen productos personalizados?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Me gustaría conocer más sobre sus productos estrella", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Pueden enviarme un catálogo de productos?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Busco productos de alta calidad", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Qué tipos de productos tienen disponibles?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Estoy interesado en sus productos tecnológicos", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Necesito productos para mejorar mi oficina", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Tienen productos en oferta?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Quiero conocer más sobre sus productos innovadores", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Pueden recomendarme algunos productos?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Estoy buscando productos para el hogar", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Qué productos nuevos han lanzado?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Necesito productos para mi tienda", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Ofrecen productos a medida?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Quisiera saber más sobre sus productos premium", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Tienen productos para pequeñas empresas?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Estoy interesado en productos sostenibles", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Busco productos con buena relación calidad-precio", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Qué productos me recomiendan?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Necesito información sobre sus productos más económicos", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Pueden ayudarme a elegir un producto?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Quiero conocer sus productos más innovadores", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Ofrecen productos para el sector industrial?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Estoy buscando productos de última generación", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Qué productos destacan en su catálogo?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Necesito productos para mejorar mi producción", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Tienen productos en stock?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Quisiera saber más sobre sus productos ecológicos", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Pueden ofrecerme detalles de sus productos?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Estoy interesado en sus productos de importación", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Busco productos con garantía extendida", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Qué productos tienen para el sector tecnológico?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Necesito productos de alta demanda", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Ofrecen productos exclusivos?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Quiero conocer sus productos más económicos", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Tienen productos para el sector educativo?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Estoy buscando productos para mejorar la seguridad", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Qué productos nuevos recomiendan?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Necesito productos para renovar mi equipo", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Pueden mostrarme sus productos más recientes?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Quisiera información sobre sus productos digitales", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Ofrecen productos con envío gratuito?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Estoy interesado en productos personalizados", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Busco productos para ampliar mi negocio", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Qué productos son ideales para emprendedores?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Necesito productos para mejorar la eficiencia", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Tienen productos con garantía?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Quiero saber más sobre sus productos de temporada", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Pueden asesorarme sobre sus productos?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Estoy buscando productos innovadores", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Qué productos tienen para pequeñas empresas?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Necesito información sobre productos en promoción", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Ofrecen productos con soporte técnico?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Quisiera conocer sus productos más recomendados", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Tienen productos disponibles ahora mismo?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Estoy interesado en productos de alta demanda", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Busco productos que se adapten a mi presupuesto", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Qué productos ofrecen para el sector salud?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Necesito productos con entrega rápida", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Pueden proporcionarme un listado de productos?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Quiero saber más sobre sus productos más vendidos", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Ofrecen productos para mejorar la productividad?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Estoy buscando productos para el sector alimentario", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Qué productos tienen con descuento?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Necesito productos para mejorar mi servicio al cliente", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Tienen productos para comercio electrónico?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Quisiera información sobre sus productos para exportación", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Pueden ayudarme a elegir el producto adecuado?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Estoy interesado en productos de alta tecnología", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Busco productos que sean fáciles de usar", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Qué productos tienen para mejorar la comunicación?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Necesito productos para capacitación", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Ofrecen productos para marketing digital?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Quiero conocer sus productos más duraderos", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Tienen productos para gestión empresarial?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Estoy buscando productos para mejorar la logística", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Qué productos ofrecen para la industria?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Necesito productos con soporte postventa", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Pueden enviarme muestras de sus productos?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Quiero saber más sobre sus productos financieros", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Ofrecen productos para mejorar la energía?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Estoy interesado en productos de calidad superior", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Busco productos con certificación", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Qué productos tienen para el sector de construcción?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Necesito productos que cumplan con normas internacionales", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Pueden asesorarme sobre qué producto elegir?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Quiero conocer sus productos más eficientes", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Tienen productos para gestión de proyectos?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Estoy buscando productos para mejorar la calidad", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Qué productos recomiendan para reducir costos?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Necesito productos para automatizar procesos", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Ofrecen productos para análisis de datos?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Quiero saber más sobre sus productos para redes sociales", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Tienen productos para gestión de recursos humanos?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Estoy interesado en productos para mejorar la satisfacción del cliente", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Busco productos que ayuden a expandir mi mercado", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Qué productos tienen para mejorar la gestión financiera?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Necesito productos para mejorar la colaboración en equipo", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Pueden ofrecerme soluciones a través de sus productos?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Quiero conocer sus productos más populares", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Ofrecen productos para inteligencia artificial?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Estoy buscando productos para mejorar mi presencia en línea", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Qué productos tienen para gestión documental?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("Necesito productos para asegurar la calidad", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    
    ("Me interesa contratar sus servicios", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("¿Qué servicios tienen disponibles?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("Busco un servicio especializado", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("¿Qué tipo de servicios ofrecen?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("Necesito información sobre sus servicios", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("¿Cuáles son los servicios más solicitados?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("Quiero saber sobre su catálogo de servicios", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("Muéstrame una lista de servicios", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("Quiero información sobre los servicios ofrecidos", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("Tienen algún servicio especial?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("Oye, ¿qué servicios tienes para ofrecer?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("Estoy buscando algo que me ayude, ¿qué tienes?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("¿Puedes contarme sobre tus servicios?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("Quiero saber qué ofreces", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("¿Qué me recomiendas?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("Necesito ayuda, ¿puedes darme una mano?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("¿Qué servicios buenos tienes?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("Cuéntame qué haces", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("¿Cómo puedes ayudarme?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("Estoy interesado en lo que ofreces", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("¿Qué onda con tus servicios?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("¿Me cuentas más sobre lo que haces?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("Ando buscando ayuda, ¿qué puedes ofrecerme?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("¿Qué tienes para mí?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("Necesito un servicio, ¿cómo me puedes ayudar?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("Dime qué servicios tienes", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("Estoy curioso sobre tus servicios", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("¿Qué puedes hacer por mí?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("Necesito una mano, ¿qué ofreces?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("¿Tienes algún servicio que me sirva?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("Cuéntame más sobre tus servicios", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("Ando en busca de ayuda, ¿qué tienes?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("¿Qué puedes ofrecerme hoy?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("Estoy interesado en tus servicios, háblame de ellos", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("¿Me puedes ayudar con algo?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("Necesito saber qué servicios ofreces", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("¿Qué haces exactamente?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("Quiero más info sobre tus servicios", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("¿Puedes ayudarme con tus servicios en mi negocio?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("Busco servicios que me puedan servir", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("¿Qué tipo de servicios tienes?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("Necesito saber en qué me puedes ayudar", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("¿Qué ofreces para alguien como yo?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("Estoy buscando servicios útiles, ¿qué tienes?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("¿Me puedes explicar tus servicios?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("Quiero saber más sobre lo que haces", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("¿En qué áreas puedes ayudarme?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("Necesito un servicio, ¿qué me ofreces?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("¿Qué servicios tienes disponibles?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("Estoy interesado en contratarte, ¿qué haces?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("¿Puedes ayudarme con algo específico?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("Quiero saber qué servicios están en oferta", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("¿Tienes algún servicio que pueda necesitar?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("Necesito información sobre tus servicios", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("¿Puedes decirme qué ofreces?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("Ando buscando servicios, ¿qué tienes?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("¿Qué servicios me recomiendas?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("Quiero saber en qué me puedes dar una mano", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("¿Tienes servicios que me puedan interesar?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("Me gustaría conocer más sobre sus servicios", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("¿Qué servicios ofrecen para empresas como la mía?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("Estoy interesado en sus servicios de consultoría", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("¿Pueden ayudarme con la estrategia de marketing?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("Busco asesoramiento profesional, ¿qué me recomiendan?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("Quiero contratar sus servicios, ¿cómo procedo?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("¿Ofrecen servicios personalizados?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("Necesito apoyo con la gestión financiera", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("¿Cómo funcionan sus servicios de asesoría?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("Quisiera saber más sobre sus paquetes de servicios", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("¿Tienen experiencia en mi industria?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("Estoy buscando servicios de capacitación", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("¿Ofrecen servicios en línea?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("Necesito consultoría legal, ¿pueden ayudarme?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("¿Cuáles son los servicios más populares que ofrecen?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("Quiero mejorar mis ventas, ¿qué servicios tienen?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("¿Pueden adaptarse a las necesidades de mi empresa?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("Busco servicios de diseño gráfico", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("¿Cómo puedo agendar una reunión para conocer sus servicios?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("Necesito ayuda con mi estrategia digital", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("¿Ofrecen servicios de soporte técnico?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("Quiero externalizar algunos servicios, ¿qué opciones tengo?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("¿Pueden brindarme un servicio integral?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("Estoy interesado en sus servicios de recursos humanos", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("¿Qué servicios recomiendan para una empresa emergente?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("Necesito asesoría en comercio exterior", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("¿Cómo adaptan sus servicios a diferentes empresas?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("Busco mejorar la productividad, ¿qué ofrecen?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("¿Ofrecen servicios de auditoría?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("Quiero conocer los detalles de sus servicios profesionales", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("¿Pueden ayudarme con la implementación de tecnología?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("Necesito servicios de logística", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("¿Tienen servicios para mejorar la atención al cliente?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("Estoy buscando servicios de capacitación para mi equipo", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("¿Cómo me pueden ayudar a expandir mi negocio?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("Quiero saber si ofrecen servicios de branding", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("¿Pueden asesorarme en temas legales?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("Necesito mejorar mi estrategia de ventas", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("¿Ofrecen servicios de traducción?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("Busco servicios de fotografía profesional", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("¿Qué soluciones me pueden ofrecer?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("Estoy interesado en servicios de formación online", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("¿Pueden proporcionarme referencias de sus servicios?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("Necesito consultoría en gestión de proyectos", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("¿Cómo personalizan sus servicios para cada cliente?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("Quiero saber más sobre su servicio al cliente", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("¿Ofrecen servicios de mantenimiento?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("Estoy buscando asesoría en inversiones", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("¿Qué servicios tienen para mejorar la eficiencia?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),
    ("Necesito ayuda con el desarrollo de mi plan de negocios", {"cats": {"product_query": 0, "service_query": 1, "price_query": 0}}),

    ("¿Cuál es el precio del producto?", {"cats": {"product_query": 0, "service_query": 0, "price_query": 1}}),
    ("¿Cuánto cuesta este servicio?", {"cats": {"product_query": 0, "service_query": 0, "price_query": 1}}),
    ("¿Me pueden decir el precio de ese producto?", {"cats": {"product_query": 0, "service_query": 0, "price_query": 1}}),
    ("¿Cuál es el costo de los servicios?", {"cats": {"product_query": 0, "service_query": 0, "price_query": 1}}),
    ("Quiero saber el precio de los productos", {"cats": {"product_query": 0, "service_query": 0, "price_query": 1}}),
    ("¿Qué precio tiene ese servicio?", {"cats": {"product_query": 0, "service_query": 0, "price_query": 1}}),
    ("¿Me das el precio del producto?", {"cats": {"product_query": 0, "service_query": 0, "price_query": 1}}),
    ("Necesito saber el precio del servicio", {"cats": {"product_query": 0, "service_query": 0, "price_query": 1}}),
    ("¿Qué precio tiene?", {"cats": {"product_query": 0, "service_query": 0, "price_query": 1}}),
    ("Dime el precio de los productos", {"cats": {"product_query": 0, "service_query": 0, "price_query": 1}}),
    ("¿Cuál es el precio de este producto?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 1}}),
    ("¿Cuánto cuesta el servicio de consultoría?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 1}}),
    ("¿Me puede dar el precio de sus productos?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 1}}),
    ("Necesito saber cuánto cobran por sus servicios", {"cats": {"product_query": 0, "service_query": 1, "price_query": 1}}),
    ("¿Cuál es el costo de este artículo?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 1}}),
    ("¿Podría informarme sobre las tarifas de sus servicios?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 1}}),
    ("Estoy interesado en el precio de su producto estrella", {"cats": {"product_query": 1, "service_query": 0, "price_query": 1}}),
    ("Quiero saber cuánto vale el servicio premium", {"cats": {"product_query": 0, "service_query": 1, "price_query": 1}}),
    ("¿Tienen una lista de precios de sus productos?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 1}}),
    ("¿Cuál es el precio por hora de sus servicios?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 1}}),
    ("¿Cuánto cuesta este paquete de productos?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 1}}),
    ("Necesito conocer las tarifas de sus servicios de mantenimiento", {"cats": {"product_query": 0, "service_query": 1, "price_query": 1}}),
    ("¿Cuál es el precio total si compro varios productos?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 1}}),
    ("¿Ofrecen descuentos en sus servicios?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 1}}),
    ("Quisiera saber el costo de este producto en particular", {"cats": {"product_query": 1, "service_query": 0, "price_query": 1}}),
    ("¿Cuánto cuesta contratar su servicio por un mes?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 1}}),
    ("¿Podría decirme el precio de este modelo?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 1}}),
    ("Estoy interesado en sus tarifas de consultoría", {"cats": {"product_query": 0, "service_query": 1, "price_query": 1}}),
    ("¿Cuál es el precio de este producto con impuestos incluidos?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 1}}),
    ("Necesito saber cuánto cuesta su servicio básico", {"cats": {"product_query": 0, "service_query": 1, "price_query": 1}}),
    ("¿Me puede dar una cotización de sus productos?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 1}}),
    ("Quiero saber el costo de sus servicios adicionales", {"cats": {"product_query": 0, "service_query": 1, "price_query": 1}}),
    ("¿Cuál es el precio unitario de este producto?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 1}}),
    ("¿Cuánto me costaría contratar sus servicios?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 1}}),
    ("Estoy comparando precios de productos similares", {"cats": {"product_query": 1, "service_query": 0, "price_query": 1}}),
    ("Necesito información sobre sus planes y precios", {"cats": {"product_query": 0, "service_query": 1, "price_query": 1}}),
    ("¿Ofrecen algún paquete de productos a mejor precio?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 1}}),
    ("¿Cuál es el precio por sus servicios si contrato por un año?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 1}}),
    ("¿Me puede enviar una lista de precios actualizada?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 1}}),
    ("Estoy interesado en saber sus tarifas horarias", {"cats": {"product_query": 0, "service_query": 1, "price_query": 1}}),
    ("¿Cuánto cuesta este producto en promoción?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 1}}),
    ("Quisiera saber el precio total de sus servicios premium", {"cats": {"product_query": 0, "service_query": 1, "price_query": 1}}),
    ("¿Cuál es el costo de envío de este producto?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 1}}),
    ("Necesito conocer los costos adicionales de sus servicios", {"cats": {"product_query": 0, "service_query": 1, "price_query": 1}}),
    ("¿Hay algún descuento por comprar varios productos?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 1}}),
    ("¿Cuánto cuesta su servicio más económico?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 1}}),
    ("Estoy interesado en el precio de este artículo en particular", {"cats": {"product_query": 1, "service_query": 0, "price_query": 1}}),
    ("¿Podría informarme sobre los costos de instalación del servicio?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 1}}),
    ("¿Cuál es el precio final después de impuestos?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 1}}),
    ("Necesito saber si sus servicios tienen algún costo oculto", {"cats": {"product_query": 0, "service_query": 1, "price_query": 1}}),
    ("¿Cuál es el precio de este producto en dólares?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 1}}),
    ("¿Cuánto me cobrarían por personalizar el servicio?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 1}}),
    ("Estoy comparando precios, ¿cuánto cuesta este producto?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 1}}),
    ("Quiero saber las tarifas mensuales de sus servicios", {"cats": {"product_query": 0, "service_query": 1, "price_query": 1}}),
    ("¿Cuál es el costo de este producto al por mayor?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 1}}),
    ("¿Ofrecen precios especiales para sus servicios en volumen?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 1}}),
    ("Necesito una cotización para este producto", {"cats": {"product_query": 1, "service_query": 0, "price_query": 1}}),
    ("¿Podría darme un presupuesto de sus servicios?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 1}}),
    ("¿Cuál es el precio promocional de este producto?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 1}}),
    ("Quisiera saber cuánto cuesta el paquete completo de servicios", {"cats": {"product_query": 0, "service_query": 1, "price_query": 1}}),
    ("¿Cuánto cuesta este producto en oferta?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 1}}),
    ("Necesito conocer los precios de sus diferentes planes de servicio", {"cats": {"product_query": 0, "service_query": 1, "price_query": 1}}),
    ("¿Ofrecen financiamiento para la compra de este producto?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 1}}),
    ("¿Cuáles son las opciones de pago para sus servicios?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 1}}),
    ("Estoy interesado en el costo total de este producto", {"cats": {"product_query": 1, "service_query": 0, "price_query": 1}}),
    ("¿Podría informarme sobre los costos de sus servicios adicionales?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 1}}),
    ("¿Cuál es el precio mínimo de sus productos?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 1}}),
    ("Quiero saber cuánto me costaría contratar su servicio por seis meses", {"cats": {"product_query": 0, "service_query": 1, "price_query": 1}}),
    ("¿Hay cargos extra al comprar este producto?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 1}}),
    ("Necesito un estimado de costos para sus servicios", {"cats": {"product_query": 0, "service_query": 1, "price_query": 1}}),
    ("¿Cuánto cuesta este producto de edición limitada?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 1}}),
    ("¿Ofrecen paquetes de servicio con descuento?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 1}}),
    ("Estoy buscando el mejor precio para este producto", {"cats": {"product_query": 1, "service_query": 0, "price_query": 1}}),
    ("¿Cuál es el precio de sus servicios de urgencia?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 1}}),
    ("Quisiera saber si el precio incluye garantía", {"cats": {"product_query": 1, "service_query": 0, "price_query": 1}}),
    ("Necesito información sobre los precios de sus servicios personalizados", {"cats": {"product_query": 0, "service_query": 1, "price_query": 1}}),
    ("¿Cuál es el costo de este producto con descuento por temporada?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 1}}),
    ("¿Cuánto cuesta actualizar al siguiente nivel de servicio?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 1}}),
    ("¿Hay algún cargo por instalación de este producto?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 1}}),
    ("Quiero saber si ofrecen precios especiales para nuevos clientes en sus servicios", {"cats": {"product_query": 0, "service_query": 1, "price_query": 1}}),
    ("¿Cuál es el precio por unidad si compro en grandes cantidades?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 1}}),
    ("Necesito conocer las tarifas de sus servicios internacionales", {"cats": {"product_query": 0, "service_query": 1, "price_query": 1}}),
    ("¿Cuánto me costaría añadir este producto a mi pedido?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 1}}),
    ("¿Podría proporcionarme sus tarifas detalladas?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 1}}),
    ("Estoy interesado en el precio final con envío incluido", {"cats": {"product_query": 1, "service_query": 0, "price_query": 1}}),
    ("¿Cuánto cobran por hora en sus servicios de consultoría?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 1}}),
    ("¿Ofrecen planes de pago para este producto?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 1}}),
    ("Quiero saber si hay costos de cancelación en sus servicios", {"cats": {"product_query": 0, "service_query": 1, "price_query": 1}}),
    ("¿Cuál es el precio de este producto en moneda local?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 1}}),
    ("Necesito información sobre sus tarifas de suscripción", {"cats": {"product_query": 0, "service_query": 1, "price_query": 1}}),
    ("¿Hay algún descuento disponible para este producto?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 1}}),
    ("¿Cuánto cuesta renovar su servicio?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 1}}),
    ("Estoy buscando opciones más económicas de sus productos", {"cats": {"product_query": 1, "service_query": 0, "price_query": 1}}),
    ("¿Cuál es el precio por una sesión de su servicio?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 1}}),
    ("¿Ofrecen reembolsos si el producto no me satisface?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 1}}),
    ("Quisiera saber si hay cargos adicionales en sus servicios", {"cats": {"product_query": 0, "service_query": 1, "price_query": 1}}),
    ("¿Cuál es el costo total incluyendo impuestos y tasas?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 1}}),
    ("Necesito saber cuánto cuesta el mantenimiento de sus servicios", {"cats": {"product_query": 0, "service_query": 1, "price_query": 1}}),
    ("¿Cuánto cuesta este producto en diferentes colores?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 1}}),
    ("¿Podría informarme sobre los planes de precios disponibles?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 1}}),
    ("Estoy interesado en el precio de este set de productos", {"cats": {"product_query": 1, "service_query": 0, "price_query": 1}}),
    ("¿Cuál es el costo de implementación de sus servicios?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 1}}),
    ("¿Hay algún cargo por devolución de este producto?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 1}}),
    ("Quiero saber si el precio incluye soporte técnico", {"cats": {"product_query": 0, "service_query": 1, "price_query": 1}}),
    ("¿Cuál es el precio de este producto en paquete familiar?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 1}}),
    ("Necesito conocer los precios para empresas de sus servicios", {"cats": {"product_query": 0, "service_query": 1, "price_query": 1}}),
    ("¿Ofrecen garantía extendida por un costo adicional en este producto?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 1}}),
    ("¿Cuánto cuesta actualizar su servicio básico al premium?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 1}}),
    ("Estoy interesado en el precio de este producto con accesorios", {"cats": {"product_query": 1, "service_query": 0, "price_query": 1}}),
    ("¿Podría proporcionarme un detalle de los costos de sus servicios?", {"cats": {"product_query": 0, "service_query": 1, "price_query": 1}}),

    # Preguntas de Lona marítima
    ("¿Cuáles son las dimensiones disponibles para la lona marítima?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Es resistente al agua y a los rayos UV?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Ustedes hacen la instalación?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Es compatible con todos los modelos de pick-up?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),

    # Preguntas de Lona jaula apoyada
    ("¿En qué vehículos se puede instalar la lona jaula apoyada?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿La estructura de la jaula viene incluida con la lona?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Es fácil de montar y desmontar?", {"cats": {"product_query": 1, "service_query": 1, "price_query": 0}}),

    # Preguntas de Jaula negra
    ("¿De qué material está fabricada la jaula negra?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Es resistente a la corrosión y al óxido?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Se puede adaptar a diferentes modelos de vehículos?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),

    # Preguntas de Jaula cromada
    ("¿Qué acabado tiene la superficie cromada de la jaula?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Requiere algún tipo de mantenimiento especial?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Es resistente a rayaduras y golpes?", {"cats": {"product_query": 1, "service_query": 1, "price_query": 0}}),

    # Preguntas de Estribos Hulk
    ("¿Cuál es la capacidad de peso que soportan los Estribos Hulk?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Están fabricados con materiales antideslizantes?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
    ("¿Se adaptan a diferentes modelos de camionetas?", {"cats": {"product_query": 1, "service_query": 0, "price_query": 0}}),
]

# Función de entrenamiento del modelo
def train_model(n_iter=10, batch_size=8):
    optimizer = nlp.begin_training()

    for i in range(n_iter):
        random.shuffle(train_data)
        losses = {}
        for text, annotations in train_data:
            # Crear el objeto Example con el texto y la anotación
            doc = nlp.make_doc(text)
            example = Example.from_dict(doc, annotations)

            # Actualizar el modelo
            nlp.update([example], sgd=optimizer, losses=losses)

        print(f"Iteración {i + 1}, Pérdida: {losses}")

    # Guardar el modelo entrenado
    output_dir = "modelo_chatbot"
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)
    nlp.to_disk(output_dir)
    print(f"Modelo guardado en '{output_dir}'")

# Llamada a la función de entrenamiento
train_model(n_iter=20, batch_size=16)